# what is hyperbololic tangent function?

import numpy as np
from lib.tensor import Tensor

class Layer:
#    Layer is the base class for all the layers in our network
#   Forward : produces o/p for corresponding inputs
# backward : takes the grad generated by loss and propogates it back to the previous layer

# constructor 
    def __init__(self)-> None:
        pass

    def forward(Self , inputs:Tensor)-> Tensor:
        raise NotImplementedError
    def backward(self , grad:Tensor)->Tensor:
        raise NotImplementedError
    
class Linear(Layer):
    # computes output 
    # output = input @ w + b
    # where @ is matrix multiplication
    # w is weight matrix
    # b is bias vector
    pass
